let a = 5;
let b = 2;
let c = a + b;
console.log("a + b =", c);
console.log("a - b =", a - b);
console.log("a * b =", a * b);
console.log("a / b =", a / b);
console.log("a % b =", a % b);
console.log("a ** b =", a ** b); //Exponentiation, a^b.
console.log("a++ =", a++);
console.log("++a =", ++a);
console.log("a-- =", a--);
console.log("--a =", --a);
